### PR TITLE
Fixed encoding issues with map names.

### PR DESCRIPTION
**Pull request by givenameplz**
EscapedUriString is not sufficient enough as it does not encode "&", UrlEncode will do the trick.

### CODE REVIEW

**Comment by Piotrekol** [comment]
is second line on this screenshot correct?
test

Adding your proposed solution would require changing project target framework.

**Comment by givenameplz** [comment]
I see. The second line is correct yes, you can go with that.

**Comment by FayneAldan** [comment]
I just noticed this as well:

As you can see, the & causes the rest of the text to be underlined. Could there be any other possible side effects?

**Comment by Piotrekol** [comment]
This is unrelated and I'm pretty sure that's just a UI display bug

**Pull request merged**
